name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-browser
        rfbrowser init

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Run Robot Framework *.robot with xvfb
      run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' robot -d output *.robot

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: output/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
        git fetch origin
        git checkout -b gh-pages
        cp -r output/* .
        git add .
        git commit -m "Deploy report to GitHub Pages"
        git push origin gh-pages --force
