name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-browser
        rfbrowser init

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Run Robot Framework *.robot with xvfb
      run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' robot *.robot

    - name: Verifier le contenu du dossier 
      run: ls

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: report.html # Robot Framework report, si non *.html
